"""Streamlit dashboard for the Market Vocabulary Agent."""

from __future__ import annotations

import os
import subprocess
import sys
from datetime import datetime
from pathlib import Path
from zoneinfo import ZoneInfo

import streamlit as st
from dotenv import load_dotenv

from app.knowledge_graph import KnowledgeGraph
from app.notes import load_notes, parse_notes, save_notes, validate_notes
from app.progress import ProgressStore

# ── project paths ─────────────────────────────────────────────────────────────

_PROJECT_ROOT = Path(__file__).resolve().parent.parent
load_dotenv(_PROJECT_ROOT / ".env")


def _resolve(raw: str) -> Path:
    p = Path(raw)
    return p if p.is_absolute() else _PROJECT_ROOT / p


_INBOX_PATH = _resolve(os.getenv("BLOOMBERG_INBOX", "data/bloomberg_inbox/today.txt"))
_OUTPUT_DIR = _resolve(os.getenv("OUTPUT_DIR", "data/outputs"))
_PROGRESS_PATH = _resolve(os.getenv("PROGRESS_DIR", "data/progress")) / "progress.json"
_GRAPH_PATH = _resolve(os.getenv("GRAPH_DIR", "data/knowledge_graph")) / "knowledge_graph.json"
_TIMEZONE = os.getenv("TIMEZONE", "America/New_York")

_BLOOMBERG_NOTICE = (
    "**External source notice:** Bloomberg Live (bloomberg.com/live) is an "
    "independent broadcast learning resource. This application is not affiliated "
    "with, endorsed by, or connected to Bloomberg L.P. or Bloomberg Media. "
    "Notes entered here are your own personal observations — not Bloomberg content. "
    "All lesson explanations, analogies, examples, and quizzes generated by this "
    "application are original content produced by the Gemini API."
)

# ── helpers ───────────────────────────────────────────────────────────────────


def _today() -> str:
    try:
        tz = ZoneInfo(_TIMEZONE)
    except Exception:
        tz = ZoneInfo("America/New_York")
    return datetime.now(tz).date().isoformat()


def _run_lesson(dry_run: bool) -> tuple[int, str, str]:
    cmd = [sys.executable, "-m", "app.main"]
    if dry_run:
        cmd.append("--dry-run")
    result = subprocess.run(
        cmd,
        capture_output=True,
        text=True,
        cwd=str(_PROJECT_ROOT),
    )
    return result.returncode, result.stdout, result.stderr


def _load_lesson_md(today: str) -> str | None:
    path = _OUTPUT_DIR / today / "lesson.md"
    return path.read_text(encoding="utf-8") if path.exists() else None


# ── page: Market Notes ────────────────────────────────────────────────────────


def page_market_notes() -> None:
    st.header("Market Notes")
    st.info(_BLOOMBERG_NOTICE)

    st.markdown(
        "Write the terms and ideas you heard while watching Bloomberg Live today — "
        "one note per line. Bullet prefixes (`-` or `*`) are optional. "
        "The lesson generator uses these notes to select relevant vocabulary terms."
    )

    raw = load_notes(_INBOX_PATH)
    edited = st.text_area(
        "Your Bloomberg notes",
        value=raw,
        height=220,
        placeholder=(
            "e.g.\n"
            "- Treasury yields rose sharply this morning.\n"
            "- I didn't understand what an inverted yield curve means.\n"
            "- NVIDIA issued stronger-than-expected forward guidance."
        ),
    )

    # Live preview
    parsed = parse_notes(edited)
    if parsed:
        with st.expander("Preview parsed notes", expanded=True):
            for note in parsed:
                st.markdown(f"- {note}")
        st.caption(f"{len(parsed)} note(s) will be sent to the lesson generator.")
    elif edited.strip():
        st.warning("No valid note lines found — check for whitespace-only lines.")

    # Save / Clear
    col_save, col_clear, _ = st.columns([1, 1, 4])
    with col_save:
        if st.button("Save notes", use_container_width=True):
            valid, reason = validate_notes(edited)
            if valid:
                save_notes(_INBOX_PATH, edited)
                st.success("Notes saved to today.txt.")
            else:
                st.error(reason)
    with col_clear:
        if st.button("Clear notes", use_container_width=True):
            save_notes(_INBOX_PATH, "")
            st.rerun()

    st.divider()
    st.subheader("Generate Lesson")

    col_dry, col_live = st.columns(2)

    with col_dry:
        st.markdown("**Dry-run** — no API call, no credits used.")
        if st.button("Run dry-run lesson", use_container_width=True):
            if edited.strip():
                valid, _ = validate_notes(edited)
                if valid:
                    save_notes(_INBOX_PATH, edited)
            with st.spinner("Generating dry-run lesson…"):
                code, out, err = _run_lesson(dry_run=True)
            if code == 0:
                st.success(out.strip())
                md = _load_lesson_md(_today())
                if md:
                    with st.expander("View generated lesson", expanded=True):
                        st.markdown(md)
            else:
                st.error(err.strip() or out.strip() or "Lesson generation failed.")

    with col_live:
        st.markdown("**Live generation** — calls the Gemini API.")
        if st.button("Run live lesson", use_container_width=True):
            if edited.strip():
                valid, _ = validate_notes(edited)
                if valid:
                    save_notes(_INBOX_PATH, edited)
            with st.spinner("Calling Gemini API…"):
                code, out, err = _run_lesson(dry_run=False)
            if code == 0:
                st.success(out.strip())
                md = _load_lesson_md(_today())
                if md:
                    with st.expander("View generated lesson", expanded=True):
                        st.markdown(md)
            else:
                st.error(err.strip() or out.strip() or "Lesson generation failed.")


# ── page: Progress ────────────────────────────────────────────────────────────


def page_progress() -> None:
    st.header("Learning Progress")

    today = _today()
    store = ProgressStore.load(_PROGRESS_PATH)
    mastered = store.mastered_terms()
    due = store.due_for_review(today)
    weakest = store.weakest_terms(n=5)

    col1, col2, col3 = st.columns(3)
    col1.metric("Terms seen", store.total_terms())
    col2.metric("Mastered (≥ 85%)", len(mastered))
    col3.metric("Due for review today", len(due))

    st.divider()

    if due:
        st.subheader("Due for review today")
        for r in sorted(due, key=lambda x: x.mastery_score):
            st.markdown(f"- **{r.term}** — mastery {r.mastery_score}%")
        st.divider()

    if weakest:
        st.subheader("Weakest terms")
        for i, r in enumerate(weakest, 1):
            st.markdown(
                f"{i}. **{r.term}** — {r.mastery_score}% mastery "
                f"({r.review_count} reviews, {r.correct_count} correct)"
            )
            st.progress(r.mastery_score / 100)
    else:
        st.info(
            "No terms reviewed yet. Generate a lesson and record quiz results "
            "with `--record-quiz` to start tracking progress."
        )

    st.divider()
    st.subheader("Record a quiz result")

    term_names = sorted(store.terms.keys()) if store.terms else []
    if term_names:
        selected_term = st.selectbox("Term", term_names)
        result = st.radio("Result", ["correct", "incorrect"], horizontal=True)
        if st.button("Record result"):
            fresh = ProgressStore.load(_PROGRESS_PATH)
            rec = fresh.record_quiz_result(
                term=selected_term,
                correct=(result == "correct"),
                today=today,
            )
            fresh.save(_PROGRESS_PATH)
            st.success(
                f"Recorded **{selected_term}** — {result}. "
                f"Mastery: {rec.mastery_score}%. "
                f"Next review: {rec.next_review_date}."
            )
            st.rerun()
    else:
        st.info("No terms in the progress store yet. Generate a lesson first.")


# ── page: Knowledge Graph ─────────────────────────────────────────────────────


def page_knowledge_graph() -> None:
    st.header("Knowledge Graph")

    graph = KnowledgeGraph.load(_GRAPH_PATH)

    if not graph.nodes:
        st.info(
            "No knowledge graph data yet. "
            "Generate a lesson to start building vocabulary connections."
        )
        return

    s = graph.stats()
    col1, col2, col3 = st.columns(3)
    col1.metric("Terms", s["total_nodes"])
    col2.metric("Connections", s["total_edges"])
    col3.metric("Categories", len(s["categories"]))

    st.divider()

    term_options = sorted(node.term for node in graph.nodes.values())
    selected = st.selectbox("Select a term to explore", term_options)

    if selected:
        from app.knowledge_graph import normalize_term
        nkey = normalize_term(selected)
        node = graph.nodes.get(nkey)

        if node:
            c1, c2, c3 = st.columns(3)
            connections = graph.connections_for_term(selected)
            c1.metric("Mastery", f"{node.mastery_score}%")
            c2.metric("Lessons seen", node.lesson_count)
            c3.metric("Connections", len(connections))

            st.markdown(f"**Definition:** {node.definition}")
            st.markdown(f"**Category:** {node.category}")
            st.caption(
                f"First seen: {node.first_seen}  |  Last seen: {node.last_seen}"
            )

            st.divider()
            st.subheader("Connections")

            strong = graph.strongest_connections(selected, n=10)
            if strong:
                for edge in strong:
                    other_key = (
                        edge.target_term
                        if edge.source_term == nkey
                        else edge.source_term
                    )
                    other_node = graph.nodes.get(other_key)
                    other_display = other_node.term if other_node else other_key
                    confidence_pct = round(edge.confidence_score * 100)
                    st.markdown(
                        f"**{other_display}** — {edge.relationship_type} · "
                        f"{confidence_pct}% · {edge.lesson_count} lesson(s)"
                    )
                    st.caption(edge.explanation)
            else:
                st.caption("No connections found for this term.")

            st.divider()
            st.subheader("Graph view")
            try:
                st.graphviz_chart(
                    graph.to_dot(focus_term=selected, max_edges=15),
                    use_container_width=True,
                )
            except Exception:
                st.caption("Install graphviz for graph visualization.")

            st.divider()
            st.subheader("Study next")
            recommendation = graph.recommend_next_term(selected)
            if recommendation:
                rec_node = graph.nodes.get(recommendation)
                rec_display = rec_node.term if rec_node else recommendation
                st.info(
                    f"Recommended next term to study: **{rec_display}** "
                    f"(lowest mastery among connections)"
                )
            else:
                st.caption("No study recommendation available for this term.")

    with st.expander("Graph statistics"):
        if s["most_connected_terms"]:
            st.markdown("**Most connected terms:**")
            for term_key, degree in s["most_connected_terms"]:
                n = graph.nodes.get(term_key)
                display = n.term if n else term_key
                st.markdown(f"- {display}: {degree} connections")

        if s["strongest_relationships"]:
            st.markdown("**Strongest relationships:**")
            for edge in s["strongest_relationships"]:
                confidence_pct = round(edge.confidence_score * 100)
                st.markdown(
                    f"- {edge.source_term} → {edge.target_term} "
                    f"[{edge.relationship_type}] {confidence_pct}%"
                )

        if s["categories"]:
            st.markdown("**Categories:**")
            for category, count in sorted(s["categories"].items()):
                st.markdown(f"- {category}: {count} term(s)")


# ── entry point ───────────────────────────────────────────────────────────────


def main() -> None:
    st.set_page_config(
        page_title="Market Vocabulary Agent",
        page_icon="📈",
        layout="wide",
    )
    st.title("Market Vocabulary Agent")

    page = st.sidebar.radio(
        "Navigate",
        ["Market Notes", "Progress", "Knowledge Graph"],
        index=0,
    )

    if page == "Market Notes":
        page_market_notes()
    elif page == "Progress":
        page_progress()
    else:
        page_knowledge_graph()


main()
